hins_camera_node:
  ros__parameters:
    address: "192.168.1.88"
    port: 8888
    # param
    gain: 246
    exposure: 33
    pwm: 50
    corrosion: 1
    # length
    length: 107
    # type
    type: 0x0100
